export const CANVAS_TYPE: '__CANVAS_TYPE__' = '__CANVAS_TYPE__';
export const CONTEXT_PROVIDER_TYPE: '__CONTEXT_PROVIDER_TYPE__' =
  '__CONTEXT_PROVIDER_TYPE__';
export const CONTEXT_CONSUMER_TYPE: '__CONTEXT_CONSUMER_TYPE__' =
  '__CONTEXT_CONSUMER_TYPE__';
